# Generated by Django 4.1.3 on 2022-12-01 18:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to=blog.models.user_directory_path, validators=[blog.models.validate_file_size]),
        ),
    ]
