# Generated by Django 4.1.3 on 2022-12-01 18:20

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to=blog.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), blog.models.validate_file_size]),
        ),
    ]
